name: rider
channels:
  - biocore
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - blast=2.12.0=pl5262h3289130_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.8.30=hbcca054_0
  - curl=7.88.1=hdbd6064_2
  - diamond=0.9.19=h2e03b76_5
  - entrez-direct=22.4=he881be0_0
  - gawk=5.1.0=h7f98852_0
  - hmmer=3.1b2=0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libcurl=7.88.1=h251f7ec_2
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.4=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - mmseqs2=13.45111=h95f258a_1
  - ncurses=6.4=h6a678d5_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openssl=3.0.15=h5eee18b_0
  - pcre=8.45=h295c915_0
  - perl=5.26.2=h14c3975_0
  - perl-archive-tar=2.32=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-common-sense=3.74=pl526_2
  - perl-compress-raw-bzip2=2.087=pl526he1b5a44_0
  - perl-compress-raw-zlib=2.087=pl526hc9558a2_0
  - perl-exporter=5.72=pl526_1
  - perl-exporter-tiny=1.002001=pl526_0
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-io-compress=2.087=pl526he1b5a44_0
  - perl-io-zlib=1.10=pl526_2
  - perl-json=4.02=pl526_0
  - perl-json-xs=2.34=pl526h6bb024c_3
  - perl-list-moreutils=0.428=pl526_1
  - perl-list-moreutils-xs=0.428=pl526_0
  - perl-pathtools=3.75=pl526h14c3975_1
  - perl-scalar-list-utils=1.52=pl526h516909a_0
  - perl-types-serialiser=1.0=pl526_2
  - perl-xsloader=0.24=pl526_0
  - pip=23.3.1=py310h06a4308_0
  - prodigal=2.6.3=hec16e2b_4
  - python=3.10.13=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - wget=1.21.4=h251f7ec_1
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.1.0
      - accelerate==0.26.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - alembic==1.13.1
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - banal==1.0.6
      - bio==1.6.2
      - biom-format==2.1.16
      - biopython==1.83
      - biothings-client==0.3.1
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - comm==0.2.1
      - contextlib2==21.6.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - dataset==1.6.2
      - datasets==2.19.2
      - debugpy==1.8.1
      - decorator==5.1.1
      - deepspeed==0.5.9
      - dill==0.3.8
      - dllogger==1.0.0
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fair-esm==2.0.0
      - filelock==3.13.1
      - fonttools==4.51.0
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - gitdb==4.0.11
      - gitpython==3.1.41
      - gprofiler-official==1.0.0
      - greenlet==3.0.3
      - h5py==3.11.0
      - hjson==3.1.0
      - huggingface-hub==0.23.3
      - idna==3.6
      - ipykernel==6.29.3
      - ipython==8.22.2
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.3.2
      - jupyter-client==8.6.0
      - jupyter-core==5.7.1
      - kiwisolver==1.4.5
      - lightning-utilities==0.11.7
      - llvmlite==0.43.0
      - mako==1.3.5
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.6
      - matplotlib-venn==1.1.1
      - ml-collections==0.1.1
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - mygene==3.2.2
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.1
      - numba==0.60.0
      - numpy==1.26.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - opentsne==1.0.1
      - packaging==23.2
      - pandas==2.2.0
      - parso==0.8.3
      - pexpect==4.9.0
      - pillow==10.3.0
      - platformdirs==4.2.0
      - pooch==1.8.0
      - prompt-toolkit==3.0.43
      - protobuf==4.25.2
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - pygments==2.17.2
      - pynndescent==0.5.13
      - pyparsing==3.1.2
      - python-dateutil==2.8.2
      - pytorch-lightning==2.4.0
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - regex==2023.12.25
      - requests==2.32.3
      - safetensors==0.4.2
      - scikit-bio==0.6.1
      - scikit-learn==1.4.0
      - scipy==1.12.0
      - sentry-sdk==1.40.2
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - sqlalchemy==1.4.52
      - stack-data==0.6.3
      - sympy==1.12
      - threadpoolctl==3.2.0
      - tokenizers==0.15.1
      - torch==2.2.0
      - torchmetrics==1.4.3
      - torchsummary==1.5.1
      - tornado==6.4
      - tqdm==4.66.1
      - traitlets==5.14.1
      - transformers==4.37.2
      - triton==2.2.0
      - typing-extensions==4.9.0
      - tzdata==2023.4
      - umap==0.1.1
      - umap-learn==0.5.6
      - urllib3==2.2.0
      - wandb==0.16.4
      - wcwidth==0.2.13
      - xxhash==3.4.1
      - yarl==1.9.4

